# Generated by Django 3.2 on 2022-01-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angioappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='angioappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ctappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ctappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='dexaappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dexaappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='fluoroappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fluoroappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mammoappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mammoappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='mriappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mriappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='nmappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='nmappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='usappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='usappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='xrayappointment',
            name='hospital_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='xrayappointment',
            name='preg_status',
            field=models.CharField(max_length=25),
        ),
    ]
