# Generated by Django 3.2 on 2022-01-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_angioappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angioappointment',
            name='exam_location',
        ),
    ]
